package com.vuong.WebNextFlix.Mode;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.id
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.full_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.user_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.user_password
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.email
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.phone
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.id
     *
     * @return the value of Users.id
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.id
     *
     * @param id the value for Users.id
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.full_name
     *
     * @return the value of Users.full_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.full_name
     *
     * @param fullName the value for Users.full_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.user_name
     *
     * @return the value of Users.user_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.user_name
     *
     * @param userName the value for Users.user_name
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.user_password
     *
     * @return the value of Users.user_password
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.user_password
     *
     * @param userPassword the value for Users.user_password
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.email
     *
     * @return the value of Users.email
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.email
     *
     * @param email the value for Users.email
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.phone
     *
     * @return the value of Users.phone
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.phone
     *
     * @param phone the value for Users.phone
     *
     * @mbg.generated Sun Nov 20 13:39:23 ICT 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}